# Generated by Django 3.2.5 on 2022-10-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modal_demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='publish_date',
        ),
    ]
